[workspace]
authors = ["HamedAlemo <h.alemohammad@gmail.com>"]
channels = ["conda-forge"]
name = "crs-tutorial"
platforms = ["osx-arm64", "osx-64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.13.*"
jupyterlab = ">=4.6.3,<5"
matplotlib = ">=3.11.1,<4"
shapely = ">=2.1.2,<3"
cartopy = ">=0.26.0,<0.27"
pystac-client = ">=0.9.0,<0.10"


